### ISSUE TITLE
automatyczne klikanie "rozumiem" po 45 zadaniach

### ISSUE THREAD

**Issue by fixedzik** [KartoniarzEssa/BetterOdrabiamyDownloader#3]
tak jak w tytule proponuje dodac automatyczne klikanie przycisku "rozumiem" na odrabiamy po 45 zadaniach, aby jeszcze bardziej zautomatyzowac dzialanie skryptu

**Comment by KartoniarzEssa** [comment]
Dokładnie nad tym myślałem przez ostatni rok, niestety nie znalazłem kompletnie żadnego sposobu na robienie tego. Mogę pomyśleć dalej ale nie obiecuję że się uda.

**Comment by KartoniarzEssa** [comment]
W sumie tak teraz trochę się z tym pobawiłem i byłoby to możliwe jednak wymagało by to eksportowania ciasteczek przez użytkownika.

**Comment by KartoniarzEssa** [comment]
@fiXedTM 
Zrobiłem to teraz bo teraz dopiero udało mi się znaleźć endpoint w api który za to odpowiada. Nwm czy jeszcze żyjesz ale informuję jak coś.
